name: event_management2
description: A modern Flutter event management UI

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  google_fonts: ^6.2.1
  lottie: ^3.1.0
  mobile_scanner: ^7.1.3
  table_calendar: ^3.2.0
  url_launcher: ^6.3.2
  google_maps_flutter: ^2.6.0


flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/